---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by win11.
--- DateTime: 2026/3/8 16:14
---

-- Redis 分布式锁释放脚本
-- 用于安全地释放 Redis 锁，确保只释放自己持有的锁
-- 参数说明:
-- KEYS[1]: 锁的 key
-- ARGV[1]: 当前线程的锁标识（UUID + 线程 ID）

-- 检查锁是否存在且锁的标识与当前线程匹配
if(redis.call('get',KEYS[1]) == ARGV[1]) then
    -- 如果锁标识匹配，说明是自己持有的锁，执行删除操作释放锁
    return redis.call('del',KEYS[1])
end 

-- 如果锁不存在或锁标识不匹配（说明是别人的锁），返回 0 表示释放失败
return 0